### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by QwertyJack** [RyanBernX/PBS#1]
偶然间看到你的文档，挺漂亮的。想参与维护这份文档。
请问你是直接编辑html的么？我感觉你应该是用了什么更高级的东西编辑的、

**Comment by RyanBernX** [comment]
不是直接写html，是利用一个叫做jemdoc的脚本生成的。
[http://jemdoc.jaboc.net/](url)

维护的话当然欢迎！问一下你也是组里面的学生吗？

**Comment by QwertyJack** [comment]
我是信息的，朋友看你的文档看不懂

**Comment by RyanBernX** [comment]
哪个地方写得不清楚可以随时在这里提问

**Comment by QwertyJack** [comment]
如果你同意帮你维护的话不妨把源码贴上。

**Comment by RyanBernX** [comment]
已添加。
