### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by QwertyJack** [RyanBernX/PBS#2]
1. MENU一个就好了，不知道你写俩是啥意思；是有什么特殊目的么？
2. 文件结构有点混乱；墙裂建议重构。
3. 192.241不是挺适合搭个网站么？干嘛还github.io？搞的每次都得连收费网关；没有域名我可以给你做一个。
4. 建议使用 GNU Make.

**Comment by RyanBernX** [comment]
1. 说的是github生成的模板首页吗？那个没什么特殊目的，会考虑去掉的。
2. 结构乱指得是src和pages里面文件重复吗？
3. 是这样的，github这边只是方便我自己更新，然后导师那边也会复制一份挂在主页上。搭网站我不太会做，能教我一下吗？
4. 说的是C程序编译的那块？目前使用这个服务器的同学几乎都是用matlab干活的，用C的人几乎没有，所以这部分就没怎么详细写，等同学有需求了再往上加也行。

**Comment by QwertyJack** [comment]
1. 我说的是 jemdoc ; 你的 src 里有两个 MENU: indexMENU和pbsMENU. 两个MENU不直观而且不太好看。我晚些时候提交一个 pull request 你一看就知道了。
2. 同1,，结合4。
3. 既然文老板有主页，可以做个自动更新的脚本；我是觉得 github.io 有点不太适合这个情况；做网页是初学者，搭网站稍微有点经验，私信联系罢。
4. 我说的是 jemdoc 的生成，建议使用 GNU make，可以做到自动生成网页、更新网页；详见 pull request.

**Comment by RyanBernX** [comment]
jemdoc那里有两个menu主要是因为一共有两页的主页，然后MENU的作用是显示在网页左侧那一列。如果写在一个文件里面那么目录结构感觉有点乱，现在你改完之后左侧出现两组目录，但是那两组目录实际上不是平行关系。我现在的想法是把“登录”那一部分做成子目录，在jemdoc的说明上好像没看到相关的说明。

github这边只是方便我临时更新，并且如果只是看网页的话貌似不用开外网，只是查看gh项目的时候要开一下。最好能搞个自动更新的脚本，如果不行再考虑自己搭一个网站，一个网页放好几个地方更新感觉有点麻烦。

makefile现在还不怎么会用，我会学习一下的。

merge之后好像pages符号链接没连上，css路径好像也得调一下。

**Comment by QwertyJack** [comment]
既然如此还不如源码网页分开

**Comment by RyanBernX** [comment]
就是我想要左侧的效果是这样的：
工作站使用方法 
   首页
   登录到工作站
       使用Linux/Mac OS
       使用Windows
   XXX

现在的效果是这样的：
登录到工作站
    使用Linux/Mac OS
    使用Windows
工作站使用指南
    XXXX

就是想要'登录到工作站'的目录在'使用方法'的里面。
估计jemdoc不支持这种格式。

**Comment by QwertyJack** [comment]
应该是不支持。
